name: Format and Lint
run-name: Check ${{ github.ref_name }} by @${{ github.actor }}

on:
  pull_request:

jobs:
  check-format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./*.js
