name: Release
run-name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: "Check out the [CHANGELOG](https://github.com/Leleat/create-gnome-extension/blob/main/CHANGELOG.md) for all the details."
  publish-npm:
    permissions:
      id-token: write
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm
      - name: Install dependencies
        run: npm ci
      - name: Publish to npm
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
