name: Link PR in commit messages
run-name: Link PR in commit messages

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  lin-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install git-filter-repo
        run: pip install git-filter-repo
      - name: Append PR link to commit messages
        run: |
          echo ${{github.event.pull_request.head.sha}}
          echo ${{github.event.pull_request.base.sha}}
